<head>	<meta charset="UTF-8">	<title>IPL MEGA CONTEST</title>	<link rel="stylesheet" href="hw2.css"></head> <body>	<header>		<h1>IPL2020 MEGA CONTEST</h1>		<nav>			<a href="https://forms.gle/mczXrjHcqdau1axeA">Dream Team</a>			<a href="https://forms.gle/6smHzV1oLd6g9uyLA">Player Battles</a>			<a href="https://forms.gle/iNTuaGbmmnDQzx57A">Picks</a>			<a href="orangecap.html" target="_blank">Orange cap</a>
	<a href="purplecap.html" target="_blank">purple cap</a>
	<a href="wallet.html" target="_blank">wallet balance</a>
</nav>	</header>		<main><!--marquee>all matches on Sunday are cancelled</marquee-->	<marquee><a href="match2.html">MI VS DC picks winner:Hema & Achuyth(56pts); player battles winner : achuyth(473pts)</a> </marquee> <marquee><a href="results.html">MI VS DC Match winner:Achuyth(466.5pts)</a></marquee>	
<br><h2><center>WINNERS<br> IPL 2020 winner: Mumbai Indians<br><br>IPL 2020 mega contest winner:Achuyth(Rs182.5)<br><br>purple cap winner:Achuyth(600pts)<br>orange cap winner:Sunil(875pts)<br></center></h2>
<!--	<aside class = "left">		<a href="https://commons.wikimedia.org/wiki/File%3AUltimate_Frisbee%2C_Jul_2009_-_17.jpg"><img src="ipl.jpeg" alt="DREAM 11 Photo" title="By Ed Yourdon [CC BY-SA 2.0 (http://creativecommons.org/licenses/by-sa/2.0)], via Wikimedia Commons"/> 			<a href="https://commons.wikimedia.org/wiki/File%3AUltimate_Frisbee_Colorado_Cup_2005.jpg"><img alt="Ultimate Frisbee Colorado Cup 2005" src="DREAM 11/512px-Ultimate_Frisbee_Colorado_Cup_2005.jpg"/></a> 			<a href="https://www.flickr.com/photos/paradisecoastie/15409853738/" title="Ultimate Frisbee"><img src="dream 11" alt="Ultimate Frisbee">  </a>		</aside>		<section class = "right"> 	-->   <!--h2>Playoffs Rules</h2>	<p>Total 4 contests are conducted dream team, player battles,picks, orange cap, purple cap</p>	<p>The rules for 1st three are known .For orange cap , purple cap the points of every batsman and bowlers in 4 playoff matches will be considered respectively.the player having high pts in batsman will get orange cap and with high pts in bowlers will get purple cap (all rounders are not considered) --><!-- <a href = "htpp://http://www.usaultimate.org/index.html">USA Ultimate</a>.</p>	<p>Other than professional tournaments, games of Ultimate are typically played without referess. Instead, players rely on "The Spirit of the Game" to encourage sportsmanship and self-officiating.</p>	<h2>Sources</h2> 	<ul>		<li><a href = "https://en.wikipedia.org/wiki/Ultimate_(sport)">Ultimate (sport)</a></li>		<li><a href = "http://www.wfdf.org/">World Flying Disc Federation</a></li>	</ul>	</section></main></body></html> -->
 	<!--center><h2>Live Score</h2></center>
<iframe src="https://www.iplt20.com/match/2020/60" height="500" title="W3Schools Free Online Web Tutorials"></iframe-->
 
  <h2><img src="logo.png" alt="points" background-color="yellow" height="50" width="50"/>Managed by harsh securities</h2><body style="background-color:yellow;">

 <!--This is comment-->

